### PR TITLE
EL-1453 django webpacker 2nd attempt after first one failed

### PR DESCRIPTION
**Pull request by starswan**
## What does this pull request do?

Replaces gulp with django-webpacker - use static link for CSS rather than webpacker generated version

## Any other changes that would benefit highlighting?

Intentionally left blank.

## Checklist

- [ ] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Comment by psweeting1** [comment]
Issues with FALA Docker `Error reading /home/app/fala/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?`

**Comment by psweeting1** [comment]
`Main.js` is not compiling GDS js

**Comment by psweeting1** [comment]
Your using hash / Fingerprint on main.js but not with the css file? How come?

**Comment by starswan** [comment]
> You're using hash / Fingerprint on main.js but not with the css file? How come?

Doing fingerprinting for CSS appears to be another challenge - the syntax for splitting main into JS and CSS doesn't seem to work for the Jinja templating support (which is poorly documented)

**Comment by MazOneTwoOne** [comment]
@starswan & @psweeting1  should we close this PR now and record the attempt on the JIRA ticket?

**Comment by MazOneTwoOne** [comment]
This PR was stopped, and looking to raise separate spike ticket, to investigate a way forward.

**Pull request closed without merging**
